import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../globals.css';
import { Layout } from '@/components/Layout';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full antialiased' suppressHydrationWarning>
      <body className='flex h-full bg-zinc-50 dark:bg-black'>
        <div className='flex w-full'>
          <Layout>{children}</Layout>
        </div>
      </body>
    </html>
  );
}
